"""
Core constants package - centralized application constants

This package reorganizes the original monolithic constants.py file into
logical, focused modules for better maintainability and discoverability.
"""

# Import all constants from submodules
from .errors import ErrorMessages, ErrorCodes
from .app import (
    AUTO_DOWNLOAD_INTERVAL,
    AUTO_IMPORT_INTERVAL,
    CLEANUP_COVERS_INTERVAL,
    DEFAULT_FUZZY_THRESHOLD,
    DEFAULT_PAGE_SIZE,
    DOWNLOAD_FILE_SEARCH_DEPTH,
    DOWNLOAD_MONITOR_INTERVAL,
    MAX_DOWNLOAD_RETRIES,
    MAX_DOWNLOADS,
    MAX_PAGE_SIZE,
    OCR_PROCESSOR_INTERVAL,
    PROVIDER_SEARCH_TIMEOUT,
    RATE_LIMIT_AUTH_CALLS,
    RATE_LIMIT_AUTH_PERIOD,
    RATE_LIMIT_CALLS,
    RATE_LIMIT_PERIOD,
    TASK_SCHEDULER_CHECK_INTERVAL,
    TITLE_MATCH_THRESHOLD,
    TOKEN_EXPIRATION_HOURS,
)
from .category import (
    CATEGORY_ARTICLES,
    CATEGORY_COMICS,
    CATEGORY_KEYWORDS,
    CATEGORY_MAGAZINES,
    CATEGORY_NEWS,
)
from .country import (
    COUNTRY_INDICATORS,
    COUNTRY_TO_LANGUAGE,
    ISO_COUNTRIES,
    LANGUAGE_TO_COUNTRY,
    REGIONAL_EDITION_INDICATORS,
)
from .date import (
    DUPLICATE_DATE_THRESHOLD_DAYS,
    MAX_VALID_YEAR,
    MIN_VALID_YEAR,
    MONTH_TO_NUMBER,
    NUMBER_TO_MONTH,
    NUMBER_TO_MONTH_ABBR,
    OCR_MONTH_NAMES,
)
from .files import (
    DEFAULT_ORGANIZATION_PATTERN,
    ISSUE_PREFIX,
    MAX_FILENAME_LENGTH,
    ORGANIZED_FILENAME_PATTERN,
    ORGANIZED_FILENAME_SEPARATOR,
    PDF_COVER_DPI,
    PDF_COVER_DPI_HIGH,
    PDF_COVER_DPI_LOW,
    PDF_COVER_QUALITY,
    PDF_COVER_QUALITY_HIGH,
    VOLUME_PREFIX,
)
from .language import (
    DEFAULT_LANGUAGE,
    LANGUAGE_CODE_MAP,
    LANGUAGE_KEYWORDS,
    LANGUAGE_TO_PADDLEOCR,
    SUPPORTED_LANGUAGES,
)
from .ocr import (
    MAX_IMAGE_PIXELS,
    OCR_BATCH_SIZE,
    OCR_CONTRAST_ENHANCE,
    OCR_DENOISE_H,
    OCR_DISABLE_ENV_VALUES,
    OCR_IMAGE_MAX_DIMENSION,
    OCR_ISSUE_PATTERNS,
    OCR_MAX_PAGES,
    OCR_MAX_WORKERS,
    OCR_RESIZE_WIDTH,
    OCR_SHARPEN_KERNEL,
    OCR_SPECIAL_EDITION_INDICATORS,
    OCR_TEXT_DETECTION_THRESHOLD,
    OCR_TEXT_UNCLIP_RATIO,
    OCR_VOLUME_PATTERNS,
    OCR_YEAR_PATTERN,
    PDF_COVER_DPI_OCR,
)

# Define __all__ for wildcard imports
__all__ = [
    # Error messages and codes
    "ErrorMessages",
    "ErrorCodes",
    # App constants
    "AUTO_DOWNLOAD_INTERVAL",
    "AUTO_IMPORT_INTERVAL",
    "CLEANUP_COVERS_INTERVAL",
    "DEFAULT_FUZZY_THRESHOLD",
    "DEFAULT_PAGE_SIZE",
    "DOWNLOAD_FILE_SEARCH_DEPTH",
    "DOWNLOAD_MONITOR_INTERVAL",
    "MAX_DOWNLOAD_RETRIES",
    "MAX_DOWNLOADS",
    "MAX_PAGE_SIZE",
    "OCR_PROCESSOR_INTERVAL",
    "PROVIDER_SEARCH_TIMEOUT",
    "RATE_LIMIT_AUTH_CALLS",
    "RATE_LIMIT_AUTH_PERIOD",
    "RATE_LIMIT_CALLS",
    "RATE_LIMIT_PERIOD",
    "TASK_SCHEDULER_CHECK_INTERVAL",
    "TITLE_MATCH_THRESHOLD",
    "TOKEN_EXPIRATION_HOURS",
    # Category constants
    "CATEGORY_ARTICLES",
    "CATEGORY_COMICS",
    "CATEGORY_KEYWORDS",
    "CATEGORY_MAGAZINES",
    "CATEGORY_NEWS",
    # Country constants
    "COUNTRY_INDICATORS",
    "COUNTRY_TO_LANGUAGE",
    "ISO_COUNTRIES",
    "LANGUAGE_TO_COUNTRY",
    "REGIONAL_EDITION_INDICATORS",
    # Date constants
    "DUPLICATE_DATE_THRESHOLD_DAYS",
    "MAX_VALID_YEAR",
    "MIN_VALID_YEAR",
    "MONTH_TO_NUMBER",
    "NUMBER_TO_MONTH",
    "NUMBER_TO_MONTH_ABBR",
    "OCR_MONTH_NAMES",
    # File constants
    "DEFAULT_ORGANIZATION_PATTERN",
    "ISSUE_PREFIX",
    "MAX_FILENAME_LENGTH",
    "ORGANIZED_FILENAME_PATTERN",
    "ORGANIZED_FILENAME_SEPARATOR",
    "PDF_COVER_DPI",
    "PDF_COVER_DPI_HIGH",
    "PDF_COVER_DPI_LOW",
    "PDF_COVER_QUALITY",
    "PDF_COVER_QUALITY_HIGH",
    "VOLUME_PREFIX",
    # Language constants
    "DEFAULT_LANGUAGE",
    "LANGUAGE_CODE_MAP",
    "LANGUAGE_KEYWORDS",
    "LANGUAGE_TO_PADDLEOCR",
    "SUPPORTED_LANGUAGES",
    # OCR constants
    "MAX_IMAGE_PIXELS",
    "OCR_BATCH_SIZE",
    "OCR_CONTRAST_ENHANCE",
    "OCR_DENOISE_H",
    "OCR_DISABLE_ENV_VALUES",
    "OCR_IMAGE_MAX_DIMENSION",
    "OCR_ISSUE_PATTERNS",
    "OCR_MAX_PAGES",
    "OCR_MAX_WORKERS",
    "OCR_RESIZE_WIDTH",
    "OCR_SHARPEN_KERNEL",
    "OCR_SPECIAL_EDITION_INDICATORS",
    "OCR_TEXT_DETECTION_THRESHOLD",
    "OCR_TEXT_UNCLIP_RATIO",
    "OCR_VOLUME_PATTERNS",
    "OCR_YEAR_PATTERN",
    "PDF_COVER_DPI_OCR",
]
